# chathook config.yml

# Should errors log full stack traces?
debug: false

# The HTTP endpoint to POST each private‐message JSON to
endpoint-url: "http://zarachat.duckdns.org:5000/receive"

# Timeout (ms) for HTTP POST
timeout-ms: 5000

# Number of retries if POST fails
retry-limit: 3

# Name of the bot
botName: ZaraSprite