name: chathook
main: com.playtheatria.chathook.Chathook
version: 1.0
description: Forwards ZaraSprite PMs to external GPT service
api-version: 1.20

commands:
  chathook:
    description: "Chathook admin commands (reload config or purge logs)"
    usage: "/chathook <reload|purge all>"
    permission: chathook.admin

permissions:
  chathook.admin:
    description: "Allows using /chathook reload and /chathook purge all"
    default: op

# Logs are now in a single rolling set: plugins/Chathook/logs/chathook-*.log
