name: chathook
version: 1.0.0
main: com.playtheatria.chathook.Chathook
api-version: "1.20"

commands:
  chathook:
    description: "Manage chathook: reload config or purge logs"
    usage: "/chathook <reload|purger <username>|purgeall>"
    permission: chathook.mod

permissions:
  # Administrators (ops by default) – full control, including granting 'mod' to others
  chathook.admin:
    description: "Full access to chathook, including assigning mod status"
    default: op
    children:
      chathook.mod: true

  # Moderators – can reload config, purge any logs, or allow users to purge their own
  chathook.mod:
    description: "Can reload config and purge logs"
    default: false
